# Generated by Django 5.1.15 on 2026-07-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('hod', 'Head of Department'), ('registrar', 'Registrar'), ('bursar', 'Bursar'), ('exam_officer', 'Exam Officer'), ('practical_coord', 'Practical Coordinator'), ('ict_admin', 'ICT Administrator'), ('super_admin', 'Super Administrator')], db_index=True, max_length=20),
        ),
    ]
