# Generated by Django 5.1.15 on 2026-07-06 14:36

import apps.core.utils.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (600, '600 Level')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[apps.core.utils.validators.validate_positive_amount])),
                ('description', models.CharField(blank=True, help_text='e.g. Tuition + Library + Sports Levy', max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='departments.department')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academics.academicsession')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['-session__name', 'department__code', 'level'],
                'constraints': [models.UniqueConstraint(fields=('department', 'level', 'session'), name='unique_fee_structure_per_dept_level_session')],
            },
        ),
    ]
