# Generated by Django 4.2.27 on 2026-09-26 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_semester_is_active_levelsemesterstate'),
        ('admissions', '0004_programme_duration_levels'),
        ('finance', '0005_feestructure_fee_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feestructure',
            name='unique_fee_structure_per_dept_level_session_type',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to every programme in the department.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='admissions.programme'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to the whole session.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academics.semester'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('department', 'level', 'session', 'fee_type', 'programme', 'semester'), name='unique_fee_structure_per_dept_level_session_type_programme_semester'),
        ),
    ]
