# Generated by Django 5.1.15 on 2026-07-11 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_level_states(apps, schema_editor):
    """Carry the old single global active semester over to the new
    per-level model: every level that currently has students or courses
    starts out pointing at whichever semester was active.
    """
    Semester = apps.get_model('academics', 'Semester')
    LevelSemesterState = apps.get_model('academics', 'LevelSemesterState')
    Student = apps.get_model('students', 'Student')
    Course = apps.get_model('courses', 'Course')

    active = Semester.objects.filter(is_active=True, is_deleted=False).first()
    if not active:
        return

    levels = set(Student.objects.values_list('level', flat=True)) | set(
        Course.objects.values_list('level', flat=True)
    )
    for level in levels:
        LevelSemesterState.objects.create(level=level, semester=active)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        ('courses', '0003_course_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelSemesterState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (600, '600 Level')], unique=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level_states', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Level Semester State',
                'verbose_name_plural': 'Level Semester States',
                'ordering': ['level'],
            },
        ),
        migrations.RunPython(seed_level_states, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='semester',
            name='is_active',
        ),
    ]
