# Generated by Django 5.1.15 on 2026-07-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, help_text='Must be a lecturer already assigned to this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='lecturers.lecturer', verbose_name='Head of Department'),
        ),
    ]
