# Generated by Django 5.1.15 on 2026-08-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_general_studies',
            field=models.BooleanField(default=False, help_text='General Studies (or similar): courses under this department are available to every student at the matching level, not just its own students. Its HOD still assigns/allocates its courses like any other HOD.'),
        ),
    ]
