# Generated by Django 5.1.15 on 2026-07-06 13:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('departments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('matric_number', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid matric number, e.g. CHE/2025/0001.', regex='^[A-Z]{2,6}/\\d{2,4}/\\d{3,6}$')])),
                ('level', models.PositiveSmallIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (600, '600 Level')], default=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated')], default='active', max_length=15)),
                ('admission_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admitted_students', to='academics.academicsession')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='departments.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['matric_number'],
            },
        ),
    ]
