# Generated by Django 5.1.15 on 2026-08-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_programme_department'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='The programme (within the department) this student is enrolled in, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='admissions.programme'),
        ),
    ]
