# Generated by Django 4.2.27 on 2026-09-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.CharField(help_text='Assigned by the Registrar - no fixed format, but must be unique.', max_length=30, unique=True),
        ),
    ]
