# Generated by Django 5.1.15 on 2026-07-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_assign_courses', 'Can assign courses to lecturers'), ('can_approve_registration', 'Can approve student course registration'), ('can_review_grades', 'Can review lecturer-submitted grades'), ('can_verify_payment', 'Can verify student payments'), ('can_compile_results', 'Can compile results'), ('can_publish_results', 'Can publish results'), ('can_generate_transcript', 'Can generate student transcripts'), ('can_approve_admission', 'Can approve student admission'), ('can_generate_matric_numbers', 'Can generate matric numbers'), ('can_activate_semester', 'Can activate an academic semester')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
