# Generated by Django 5.1.15 on 2026-08-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_programme_department'),
        ('courses', '0003_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='The programme (within the department) this course belongs to, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='admissions.programme'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_name',
            field=models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], default='first', help_text='Which semester this course is normally taught in - a Course Offering for this course can only be created in a matching semester.', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='e.g. CHE101.', max_length=20, unique=True),
        ),
    ]
