# Generated by Django 5.1.15 on 2026-08-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_programme_department'),
        ('courses', '0004_course_programme_course_semester_name_and_more'),
        ('departments', '0004_seed_general_studies'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='eligible_departments',
            field=models.ManyToManyField(blank=True, help_text="Extra departments (besides this course's own Department above) whose students may also register for it - e.g. a General Studies course taken by several departments. Leave blank for an ordinary single-department course.", related_name='cross_listed_courses', to='departments.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='eligible_programmes',
            field=models.ManyToManyField(blank=True, help_text="Extra programmes (besides this course's own Programme above) whose students may also register for it. Leave blank for an ordinary course.", related_name='cross_listed_courses', to='admissions.programme'),
        ),
    ]
