# Generated by Django 4.2.27 on 2026-09-25 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_student_programme'),
        ('academics', '0002_remove_semester_is_active_levelsemesterstate'),
        ('courses', '0005_course_eligible_departments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_approvals', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_approvals', to='students.student')),
            ],
            options={
                'verbose_name': 'Registration Approval',
                'verbose_name_plural': 'Registration Approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='registrationapproval',
            constraint=models.UniqueConstraint(fields=('student', 'semester'), name='unique_approval_per_student_semester'),
        ),
    ]
