# Generated by Django 5.1.15 on 2026-07-27 14:11

import apps.core.utils.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('short_code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(db_index=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.applicant')),
            ],
            options={
                'verbose_name': 'Admission Payment',
                'verbose_name_plural': 'Admission Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('state_of_origin', models.CharField(blank=True, max_length=100)),
                ('lga_of_origin', models.CharField(blank=True, max_length=100)),
                ('home_address', models.TextField(blank=True)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_address', models.TextField(blank=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='admissions/passports/', validators=[apps.core.utils.validators.validate_image_file])),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('section_a_complete', models.BooleanField(default=False)),
                ('section_b_complete', models.BooleanField(default=False)),
                ('section_c_complete', models.BooleanField(default=False)),
                ('section_d_complete', models.BooleanField(default=False)),
                ('section_e_complete', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='admissions.applicant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('programme_first_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_choice_applications', to='admissions.programme')),
                ('programme_second_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_choice_applications', to='admissions.programme')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('batch_label', models.CharField(blank=True, max_length=100)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_referral_codes', to='admissions.applicant')),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='referral_code_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='admissions.referralcode'),
        ),
        migrations.CreateModel(
            name='SchoolAttended',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('school_name', models.CharField(max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools_attended', to='admissions.application')),
            ],
            options={
                'verbose_name': 'School Attended',
                'verbose_name_plural': 'Schools Attended',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SSCESitting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sitting_number', models.PositiveSmallIntegerField()),
                ('exam_type', models.CharField(blank=True, choices=[('waec', 'WAEC'), ('neco', 'NECO'), ('nabteb', 'NABTEB')], max_length=10)),
                ('exam_year', models.PositiveIntegerField(blank=True, null=True)),
                ('exam_number', models.CharField(blank=True, max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssce_sittings', to='admissions.application')),
            ],
            options={
                'verbose_name': 'SSCE Sitting',
                'verbose_name_plural': 'SSCE Sittings',
                'ordering': ['sitting_number'],
            },
        ),
        migrations.CreateModel(
            name='SSCESubjectResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='admissions.sscesitting')),
            ],
            options={
                'verbose_name': 'SSCE Subject Result',
                'verbose_name_plural': 'SSCE Subject Results',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('ssce_result', 'SSCE Result Slip'), ('birth_certificate', 'Birth Certificate'), ('lga_certificate', 'LGA Certificate of Origin'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to='admissions/documents/', validators=[apps.core.utils.validators.validate_document_file])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
            ],
            options={
                'verbose_name': 'Uploaded Document',
                'verbose_name_plural': 'Uploaded Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sscesitting',
            constraint=models.UniqueConstraint(fields=('application', 'sitting_number'), name='unique_sitting_per_application'),
        ),
    ]
