# Generated by Django 5.1.15 on 2026-08-13 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_seed_programmes'),
        ('departments', '0003_department_is_general_studies'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='departments.department'),
        ),
    ]
