# Generated by Django 5.1.15 on 2026-08-13 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_programme_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='duration_levels',
            field=models.PositiveSmallIntegerField(default=4, help_text='How many levels this programme runs, starting from 100 Level - e.g. a 2-year Certificate is 2 (100 & 200 Level only); a 3-year Diploma is 3 (100-300 Level); a full 4-year programme is 4. Drives the Level/Semester breakdown shown under this programme on the HOD dashboard and course allocation.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
