# Generated by Django 5.1.15 on 2026-07-09 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0005_feestructure_fee_type'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('other_names', models.CharField(blank=True, help_text='Middle name(s), if any - shown as OTHERNAMES on the sheet.', max_length=100)),
                ('cadre', models.CharField(blank=True, max_length=50)),
                ('state_of_practical', models.CharField(blank=True, max_length=50)),
                ('lga_of_practical', models.CharField(blank=True, max_length=50)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practical_placement', to='finance.invoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_placements', to='students.student')),
            ],
            options={
                'verbose_name': 'Practical Placement',
                'verbose_name_plural': 'Practical Placements',
                'ordering': ['student__matric_number'],
            },
        ),
    ]
